### ISSUE TITLE
CntMine 무한재귀

### ISSUE THREAD

**Issue by HyeIn-Kim** [HyeIn-Kim/MineSweeper#3]
play.c의 CntMine 함수에서 무한재귀가 일어납니다.
디버깅 결과 cnt가 0일 때 CntMine을 재귀호출하면서 그 안에서 빠져나오지 못하고 있어요. (cnt가 0이 아니라면 정상 동작합니다.) @woozu99 
`if (cnt == 0) {
		for (checkrow = row - 1; checkrow <= row + 1; checkrow++) {
			if (checkrow >= 0 && checkrow < boardRows) {
				for (checkcol = col - 1; checkcol <= col + 1; checkcol++) {
					if (checkcol >= 0 && checkcol < boardCols) {
						if (my_Board[checkrow][checkcol].statusBlock == STATUS_CLOSE) {
							my_Board[checkrow][checkcol].statusBlock == STATUS_OPEN;
							CntMine(my_Board, checkrow, checkcol, boardRows, boardCols);
						}
					}
				}
			}
		}
	}`

**Comment by woozu99** [comment]
월요일 내로 수정하겠습니다.

**Comment by woozu99** [comment]
수정하였습니다.
