### ISSUE TITLE
FlagBlock 연 칸을 깃발해제할때 다시 닫히는 오류

### ISSUE THREAD

**Issue by HyeIn-Kim** [HyeIn-Kim/MineSweeper#5]
FlagBlock() 에서
OPEN인 칸에 깃발을 꽂고 다시 깃발을 해제하면
칸이 다시 닫힙니다

깃발을 뺄 때
연 칸이면 연 칸으로 바꾸고
닫힌 칸이면 닫힌 칸으로 바꾸도록 수정해 주세요.

**Comment by woozu99** [comment]
FlagBlock함수에서 처음부터 열린 칸은 깃발이 꽂히지 않게 하면 어떨까요?
깃발을 뺄 때 연 칸인지 아닌지를 확인하려면 이전 상태를 저장하는 변수가 따로 또 필요할 것 같습니다.

**Comment by HyeIn-Kim** [comment]
다른 지뢰찾기로 테스트해본 결과 연 칸에는 깃발이 꽂히지 않았습니다.
도영님 의견을 반영해서 연 칸에는 깃발이 꽂히지 않게끔 수정하였습니다.
