### ISSUE TITLE
Play함수 while 조건 오류

### ISSUE THREAD

**Issue by woozu99** [HyeIn-Kim/MineSweeper#6]
IsVictory반환값이 승리면 1, 승리가 아니면 0인데 게임을 진행시키는 while문이 IsVictory가 1일 경우 돌도록 되어있습니다.(조건을 IsVictory가 0일 경우로 바꿔야 될 것 같아요.)

@HyeIn-Kim 

`while (IsVictory(my_Board, boardRows, boardCols)) {
		do {
			printf("\nPlease Enter Rows 0~%d / Cols 0~%d: ", boardRows - 1, boardCols - 1);
			scanf_s(" %d %d", &row, &col);
		} while (!checkRowsinGame(row, boardRows) || !checkColsinGame(col, boardCols));

		if (init == 0) {
			MineAllocate(*my_Board, boardRows, boardCols, row, col);
			DrawBoard(*my_Board, boardRows, boardCols);
			init = 1;
		}

		do {
			printf("\nSelect your action (1: Open Block / 2: Flag):");
			scanf_s(" %d", &action);
		} while (!ActionInRange(action));

		switch (action) {
			case 1: 
				if (OpenBlock(my_Board, row, col, boardRows, boardCols)) {
					return;
				}
				break;
			case 2:
				FlagBlock(row, col, my_Board);
				break;
		}

		DrawBoard(*my_Board, boardRows, boardCols);
	}`

**Comment by HyeIn-Kim** [comment]
확인했습니다.
제가 함수 반환값을 잘못 이해하고 있었나 봅니다.
수정하겠습니다! (완료한 뒤 다시 답글 달게요!)

**Comment by HyeIn-Kim** [comment]
while 조건을 IsVictory()에서 !IsVictory()로 수정하였습니다.
