### ISSUE TITLE
Play함수 내부 IsVictory함수 사용 위치 문제

### ISSUE THREAD

**Issue by woozu99** [HyeIn-Kim/MineSweeper#7]
Play 함수 내부에서 IsVictory 함수가 while문이 처음 돌 때 폭탄이 할당이 아직 안 된 상태에서 실행되어 쓰레기값을 검사합니다.
@HyeIn-Kim 

`while (IsVictory(my_Board, boardRows, boardCols)) {
	do {
		printf("\nPlease Enter Rows 0~%d / Cols 0~%d: ", boardRows - 1, boardCols - 1);
		scanf_s(" %d %d", &row, &col);
	} while (!checkRowsinGame(row, boardRows) || !checkColsinGame(col, boardCols));

	if (init == 0) {
		MineAllocate(*my_Board, boardRows, boardCols, row, col);
		DrawBoard(*my_Board, boardRows, boardCols);
		init = 1;
	}

	do {
		printf("\nSelect your action (1: Open Block / 2: Flag):");
		scanf_s(" %d", &action);
	} while (!ActionInRange(action));

	switch (action) {
		case 1: 
			if (OpenBlock(my_Board, row, col, boardRows, boardCols)) {
				return;
			}
			break;
		case 2:
			FlagBlock(row, col, my_Board);
			break;
	}

	DrawBoard(*my_Board, boardRows, boardCols);
}`

**Comment by HyeIn-Kim** [comment]
기존에 while 문이던 Play 함수를 do-while문으로 수정하여
IsVictory()에 쓰레기값이 들어가지 않도록 수정하였습니다.
