### ISSUE TITLE
IsVictory 지뢰를 안 찾아도 게임이 끝나는 오류

### ISSUE THREAD

**Issue by HyeIn-Kim** [HyeIn-Kim/MineSweeper#8]
![image](https://user-images.githubusercontent.com/25563077/58268847-343bb880-7dc1-11e9-8ef2-3a4b209f2395.png)
해당 화면은 임시로 지뢰 여부를 표시하였습니다.
지뢰를 다 찾지 않았음에도 게임이 끝나는 오류가 발생합니다. @woozu99 

현재 IsVictory 함수의 게임 지속 조건은
1) STATUS_CLOSE이거나 STATUS_FLAG인 블록 중에서
2) 지뢰가 없는 칸이 있을 경우
입니다.

![image](https://user-images.githubusercontent.com/25563077/58268911-55040e00-7dc1-11e9-878d-0533e23cf794.png)
저 3*3 맵에서 (2,0)을 열면
지뢰를 제외한 모든 칸이 열리고,
남은 칸은 STATUS_CLOSE이나 지뢰가 있는 칸이라
IsVictory 함수가 게임이 끝나지 않았는데도 승리라고 판단합니다.

게임 지속 조건을
STATUS_CLOSE (지뢰 여부 상관 없이) 칸이 남아있거나,
STATUS_FLAG 중에서 지뢰가 없는 칸이 있다면
으로 STATUS마다 쪼개야 한다고 생각합니다.

**Comment by woozu99** [comment]
![KakaoTalk_20190524_013847096](https://user-images.githubusercontent.com/48882165/58312698-cfc33c80-7e46-11e9-819c-619bfa01fcd1.jpg)

IsVictory 함수는 닫힌 칸 중에 NOMAL이 존재하지 않을 경우 게임을 종료시키는 함수이기 때문에
작동은 정상적으로 됩니다.
게임이 시작하자마자 종료되는 것은 한번의 클릭으로 모든 칸이 열리기 때문이라서
최소 게임판을 3*3보다 크게 한다면 이런 케이스 발생 확률이 줄어들 것이라고 생각합니다.
