### ISSUE TITLE
retry시 Play함수 내에서 MineAllocate함수가 실행되지 안되는 오류

### ISSUE THREAD

**Issue by woozu99** [HyeIn-Kim/MineSweeper#9]
저희 retry할 때 play함수에서 init이 다시 초기화가 안돼서 지뢰가 재배치가 안되는 버그가 있어요. 이 사진은 지뢰 여부랑 칸이 열렸는지 ox로 표시해 논 것입니다.
<img width="299" alt="1212" src="https://user-images.githubusercontent.com/48882165/58325581-1c1d7500-7e65-11e9-8336-cf431c5c796c.PNG">

**Comment by hann3** [comment]
play 내 static int로 선언되어 있던 init(사용자 최초 입력 체크)의 자료형을 int로 수정함으로써 해결하였습니다
